# Generated by Django 4.2.10 on 2026-03-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='pets_app.mascota')),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_match', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('mascota1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_mascota1', to='pets_app.mascota')),
                ('mascota2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_mascota2', to='pets_app.mascota')),
            ],
            options={
                'db_table': 'matches',
                'unique_together': {('mascota1', 'mascota2')},
            },
        ),
    ]
