# Generated by Django 4.2.10 on 2026-04-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='motivo',
            field=models.TextField(max_length=1000),
        ),
    ]
