sonar.projectKey=pawmatch-backend
sonar.projectName=PawMatch Backend
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/migrations/**,**/staticfiles/**,**/media/**,**/logs/**,manage.py,**/__pycache__/**,**/tests/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
