# Generated by Django 4.2.10 on 2026-03-15 08:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('pref_id', models.AutoField(primary_key=True, serialize=False)),
                ('especie_pref', models.CharField(max_length=50)),
                ('edad_pref_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('edad_pref_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('género_pref', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('Indistinto', 'Indistinto')], max_length=10)),
                ('distancia_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preferencias',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('mascota_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('género', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('Otro', 'Otro')], max_length=10)),
                ('descripción', models.TextField(blank=True, null=True)),
                ('foto_url', models.CharField(max_length=255)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
        migrations.CreateModel(
            name='FotoMascota',
            fields=[
                ('foto_id', models.AutoField(primary_key=True, serialize=False)),
                ('foto_url', models.CharField(max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pets_app.mascota')),
            ],
            options={
                'db_table': 'fotos_mascotas',
            },
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['especie'], name='idx_especie'),
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['edad'], name='idx_edad'),
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['género'], name='idx_género'),
        ),
    ]
