# Generated by Django 4.2.10 on 2026-04-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0002_alter_mascota_foto_url_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='ubicación',
            field=models.CharField(blank=True, default='0,0', max_length=255),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripción',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
