# Generated by Django 4.2.10 on 2026-03-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_dueño_biografia_dueño_ciudad_dueño_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='password',
            field=models.CharField(db_column='contraseña', max_length=255),
        ),
    ]
