# Generated by Django 4.2.10 on 2026-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_dueño_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login', null=True),
        ),
    ]
