# Generated by Django 4.2.10 on 2026-03-21 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_dueño_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEvento',
            fields=[
                ('evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('login_ok', 'Login exitoso'), ('login_fallo', 'Login fallido'), ('registro', 'Registro de usuario'), ('logout', 'Cierre de sesión'), ('oauth_google', 'Login con Google'), ('oauth_facebook', 'Login con Facebook'), ('perfil_actualizado', 'Perfil actualizado'), ('mascota_creada', 'Mascota creada'), ('mascota_eliminada', 'Mascota eliminada'), ('like_enviado', 'Like enviado'), ('match_formado', 'Match formado'), ('mensaje_enviado', 'Mensaje enviado'), ('acceso_denegado', 'Acceso denegado')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora_eventos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['accion'], name='idx_bitacora_accion'), models.Index(fields=['usuario'], name='idx_bitacora_usuario'), models.Index(fields=['fecha'], name='idx_bitacora_fecha')],
            },
        ),
    ]
