# Generated by Django 4.2.10 on 2026-04-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_tokenactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'password_reset_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code'], name='idx_reset_email_code'), models.Index(fields=['created_at'], name='idx_reset_created')],
            },
        ),
    ]
